services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Ecommerce'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_api:/var/lib/postgresql/data
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      retries: 3
      interval: 10s
      timeout: 3s
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    depends_on:
      discovery-service:
        condition: d
    environment:
      CONFIG_SERVICE_URL: http://discovery-service:8761/eureka
      DISCOVERY_SERVICE_URL: http://config-service:9999

  account-service:
    build:




